version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Gatsby Build
          command: yarn build
      - run:
          name: deploy
          command: npx ftp-deploy
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"failed\" } }" https://webhooks.datocms.com/35b49098806ddcb05433/deploy-results'
          when: on_fail
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"success\" } }" https://webhooks.datocms.com/35b49098806ddcb05433/deploy-results'
          when: on_success